### ISSUE TITLE
Is there any update?

### ISSUE THREAD

**Issue by hzcheney** [lizeyan/Zotero-meta-update#1]
Hi, lizeyan! Is there any update on this project? I am really interested in this plugin since I am planning to update existing Zotero metadata and I found this repo. If there is any I  can help with, please let me in. :)

**Comment by lizeyan** [comment]
I just found doing this is much harder than I thought. I will finish this when I have time.
I cannot find a good database that contains all the fields, especially the official proceeding name, conference name, and series. I have tried DBLP and OpenAlex.

**Comment by hzcheney** [comment]
Have you ever used this [tool?](https://github.com/yuchenlin/rebiber) It contains a collection of many conference proceedings and most of them are from the deep learning field. I hope this may be an alternative one for the current time.

**Comment by lizeyan** [comment]
I create the first working version, but it is not fully tested. See https://github.com/lizeyan/Zotero-meta-update/tree/dev
I use CrossRef and DBLP now.
Welcome to contribute.
